app:
  frontend-url: http://localhost:3000

spring:
  application:
    name: event-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/events_service}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:}

  jpa:
    hibernate:
      ddl-auto: update

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}

server:
  port: 8081

outbox:
  relay:
    delay-ms: ${OUTBOX_RELAY_DELAY_MS:1000}

springdoc:
  swagger-ui:
    operations-sorter: method
    tags-sorter: alpha