spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: email-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/email_service}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    listener:
      simple:
        acknowledge-mode: auto
        default-requeue-rejected: false
        prefetch: 5
        concurrency: 2
        max-concurrency: 4
        retry:
          enabled: true
          stateless: true
          max-retries: 3
          initial-interval: 2s
          multiplier: 2.0
          max-interval: 30s

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT:465}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}

    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

server:
  port: ${SERVER_PORT:8082}

app:
  mail:
    from: ${MAIL_FROM}
